/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SessionKeyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCallers"
      | "createSessionKey"
      | "isValidSessionKey"
      | "owner"
      | "revokeSessionKey"
      | "sessionKeys"
      | "setAuthorizedCaller"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SessionKeyCreated"
      | "SessionKeyRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSessionKey",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSessionKey",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeSessionKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionKeys",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionKeyCreatedEvent {
  export type InputTuple = [key: AddressLike, expiry: BigNumberish];
  export type OutputTuple = [key: string, expiry: bigint];
  export interface OutputObject {
    key: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionKeyRevokedEvent {
  export type InputTuple = [key: AddressLike];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SessionKey extends BaseContract {
  connect(runner?: ContractRunner | null): SessionKey;
  waitForDeployment(): Promise<this>;

  interface: SessionKeyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  createSessionKey: TypedContractMethod<
    [
      key: AddressLike,
      durationSeconds: BigNumberish,
      maxTradeSize: BigNumberish,
      allowedPairs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  isValidSessionKey: TypedContractMethod<
    [key: AddressLike, pair: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  revokeSessionKey: TypedContractMethod<
    [key: AddressLike],
    [void],
    "nonpayable"
  >;

  sessionKeys: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        expiry: bigint;
        maxTradeSize: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createSessionKey"
  ): TypedContractMethod<
    [
      key: AddressLike,
      durationSeconds: BigNumberish,
      maxTradeSize: BigNumberish,
      allowedPairs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidSessionKey"
  ): TypedContractMethod<
    [key: AddressLike, pair: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeSessionKey"
  ): TypedContractMethod<[key: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessionKeys"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        expiry: bigint;
        maxTradeSize: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SessionKeyCreated"
  ): TypedContractEvent<
    SessionKeyCreatedEvent.InputTuple,
    SessionKeyCreatedEvent.OutputTuple,
    SessionKeyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SessionKeyRevoked"
  ): TypedContractEvent<
    SessionKeyRevokedEvent.InputTuple,
    SessionKeyRevokedEvent.OutputTuple,
    SessionKeyRevokedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SessionKeyCreated(address,uint256)": TypedContractEvent<
      SessionKeyCreatedEvent.InputTuple,
      SessionKeyCreatedEvent.OutputTuple,
      SessionKeyCreatedEvent.OutputObject
    >;
    SessionKeyCreated: TypedContractEvent<
      SessionKeyCreatedEvent.InputTuple,
      SessionKeyCreatedEvent.OutputTuple,
      SessionKeyCreatedEvent.OutputObject
    >;

    "SessionKeyRevoked(address)": TypedContractEvent<
      SessionKeyRevokedEvent.InputTuple,
      SessionKeyRevokedEvent.OutputTuple,
      SessionKeyRevokedEvent.OutputObject
    >;
    SessionKeyRevoked: TypedContractEvent<
      SessionKeyRevokedEvent.InputTuple,
      SessionKeyRevokedEvent.OutputTuple,
      SessionKeyRevokedEvent.OutputObject
    >;
  };
}
