/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvedSmartAccounts"
      | "deposit"
      | "depositNative"
      | "executeTrade"
      | "getBalance"
      | "owner"
      | "relay"
      | "setApprovedSmartAccount"
      | "setRelay"
      | "settleTradeAndPayout"
      | "settleTradeRecord"
      | "transferOwnership"
      | "withdraw"
      | "withdrawNative"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceDebited"
      | "Deposit"
      | "OwnershipTransferred"
      | "TradePayout"
      | "TradeRequested"
      | "TradeSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvedSmartAccounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTrade",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setApprovedSmartAccount",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTradeAndPayout",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTradeRecord",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvedSmartAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovedSmartAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleTradeAndPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleTradeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
}

export namespace BalanceDebitedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    balanceAfter: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    balanceAfter: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    balanceAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradePayoutEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    txHash: string
  ];
  export type OutputTuple = [user: string, amount: bigint, txHash: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRequestedEvent {
  export type InputTuple = [
    user: AddressLike,
    pair: BytesLike,
    qty: BigNumberish,
    side: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    pair: string,
    qty: bigint,
    side: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    pair: string;
    qty: bigint;
    side: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeSettledEvent {
  export type InputTuple = [
    user: AddressLike,
    pair: BytesLike,
    qty: BigNumberish,
    side: BigNumberish,
    txHash: string
  ];
  export type OutputTuple = [
    user: string,
    pair: string,
    qty: bigint,
    side: bigint,
    txHash: string
  ];
  export interface OutputObject {
    user: string;
    pair: string;
    qty: bigint;
    side: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vault extends BaseContract {
  connect(runner?: ContractRunner | null): Vault;
  waitForDeployment(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvedSmartAccounts: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositNative: TypedContractMethod<[], [void], "payable">;

  executeTrade: TypedContractMethod<
    [user: AddressLike, pair: BytesLike, qty: BigNumberish, side: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  relay: TypedContractMethod<[], [string], "view">;

  setApprovedSmartAccount: TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setRelay: TypedContractMethod<[relay_: AddressLike], [void], "nonpayable">;

  settleTradeAndPayout: TypedContractMethod<
    [
      user: AddressLike,
      pair: BytesLike,
      qty: BigNumberish,
      side: BigNumberish,
      txHash: string
    ],
    [void],
    "nonpayable"
  >;

  settleTradeRecord: TypedContractMethod<
    [
      user: AddressLike,
      pair: BytesLike,
      qty: BigNumberish,
      side: BigNumberish,
      txHash: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvedSmartAccounts"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "executeTrade"
  ): TypedContractMethod<
    [user: AddressLike, pair: BytesLike, qty: BigNumberish, side: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relay"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setApprovedSmartAccount"
  ): TypedContractMethod<
    [account: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelay"
  ): TypedContractMethod<[relay_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleTradeAndPayout"
  ): TypedContractMethod<
    [
      user: AddressLike,
      pair: BytesLike,
      qty: BigNumberish,
      side: BigNumberish,
      txHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleTradeRecord"
  ): TypedContractMethod<
    [
      user: AddressLike,
      pair: BytesLike,
      qty: BigNumberish,
      side: BigNumberish,
      txHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BalanceDebited"
  ): TypedContractEvent<
    BalanceDebitedEvent.InputTuple,
    BalanceDebitedEvent.OutputTuple,
    BalanceDebitedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TradePayout"
  ): TypedContractEvent<
    TradePayoutEvent.InputTuple,
    TradePayoutEvent.OutputTuple,
    TradePayoutEvent.OutputObject
  >;
  getEvent(
    key: "TradeRequested"
  ): TypedContractEvent<
    TradeRequestedEvent.InputTuple,
    TradeRequestedEvent.OutputTuple,
    TradeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TradeSettled"
  ): TypedContractEvent<
    TradeSettledEvent.InputTuple,
    TradeSettledEvent.OutputTuple,
    TradeSettledEvent.OutputObject
  >;

  filters: {
    "BalanceDebited(address,uint256,uint256)": TypedContractEvent<
      BalanceDebitedEvent.InputTuple,
      BalanceDebitedEvent.OutputTuple,
      BalanceDebitedEvent.OutputObject
    >;
    BalanceDebited: TypedContractEvent<
      BalanceDebitedEvent.InputTuple,
      BalanceDebitedEvent.OutputTuple,
      BalanceDebitedEvent.OutputObject
    >;

    "Deposit(address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TradePayout(address,uint256,string)": TypedContractEvent<
      TradePayoutEvent.InputTuple,
      TradePayoutEvent.OutputTuple,
      TradePayoutEvent.OutputObject
    >;
    TradePayout: TypedContractEvent<
      TradePayoutEvent.InputTuple,
      TradePayoutEvent.OutputTuple,
      TradePayoutEvent.OutputObject
    >;

    "TradeRequested(address,bytes32,uint256,uint8,uint256)": TypedContractEvent<
      TradeRequestedEvent.InputTuple,
      TradeRequestedEvent.OutputTuple,
      TradeRequestedEvent.OutputObject
    >;
    TradeRequested: TypedContractEvent<
      TradeRequestedEvent.InputTuple,
      TradeRequestedEvent.OutputTuple,
      TradeRequestedEvent.OutputObject
    >;

    "TradeSettled(address,bytes32,uint256,uint8,string)": TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
    TradeSettled: TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
  };
}
