/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SmartAccountFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountOf"
      | "createAccount"
      | "entryPoint"
      | "sessionKeyStore"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SmartAccountCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "accountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sessionKeyStore",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "accountOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sessionKeyStore",
    data: BytesLike
  ): Result;
}

export namespace SmartAccountCreatedEvent {
  export type InputTuple = [owner: AddressLike, account: AddressLike];
  export type OutputTuple = [owner: string, account: string];
  export interface OutputObject {
    owner: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartAccountFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SmartAccountFactory;
  waitForDeployment(): Promise<this>;

  interface: SmartAccountFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  createAccount: TypedContractMethod<
    [owner: AddressLike],
    [string],
    "nonpayable"
  >;

  entryPoint: TypedContractMethod<[], [string], "view">;

  sessionKeyStore: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<[owner: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sessionKeyStore"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "SmartAccountCreated"
  ): TypedContractEvent<
    SmartAccountCreatedEvent.InputTuple,
    SmartAccountCreatedEvent.OutputTuple,
    SmartAccountCreatedEvent.OutputObject
  >;

  filters: {
    "SmartAccountCreated(address,address)": TypedContractEvent<
      SmartAccountCreatedEvent.InputTuple,
      SmartAccountCreatedEvent.OutputTuple,
      SmartAccountCreatedEvent.OutputObject
    >;
    SmartAccountCreated: TypedContractEvent<
      SmartAccountCreatedEvent.InputTuple,
      SmartAccountCreatedEvent.OutputTuple,
      SmartAccountCreatedEvent.OutputObject
    >;
  };
}
