/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Lite__factory } from "./IERC20Lite__factory";
export { OwnableLite__factory } from "./OwnableLite__factory";
