/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISessionKeyStoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSessionKey"
      | "isValidSessionKey"
      | "revokeSessionKey"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createSessionKey",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSessionKey",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSessionKey",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeSessionKey",
    data: BytesLike
  ): Result;
}

export interface ISessionKeyStore extends BaseContract {
  connect(runner?: ContractRunner | null): ISessionKeyStore;
  waitForDeployment(): Promise<this>;

  interface: ISessionKeyStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSessionKey: TypedContractMethod<
    [
      key: AddressLike,
      durationSeconds: BigNumberish,
      maxTradeSize: BigNumberish,
      allowedPairs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  isValidSessionKey: TypedContractMethod<
    [key: AddressLike, pair: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  revokeSessionKey: TypedContractMethod<
    [key: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSessionKey"
  ): TypedContractMethod<
    [
      key: AddressLike,
      durationSeconds: BigNumberish,
      maxTradeSize: BigNumberish,
      allowedPairs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidSessionKey"
  ): TypedContractMethod<
    [key: AddressLike, pair: BytesLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeSessionKey"
  ): TypedContractMethod<[key: AddressLike], [void], "nonpayable">;

  filters: {};
}
