/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISessionKeyAdmin,
  ISessionKeyAdminInterface,
} from "../../../contracts/SmartAccountFactory.sol/ISessionKeyAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
    ],
    name: "setAuthorizedCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISessionKeyAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): ISessionKeyAdminInterface {
    return new Interface(_abi) as ISessionKeyAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISessionKeyAdmin {
    return new Contract(address, _abi, runner) as unknown as ISessionKeyAdmin;
  }
}
