/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockEntryPoint,
  MockEntryPointInterface,
} from "../../../contracts/mocks/MockEntryPoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    name: "addStake",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "depositTo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "unlockStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    name: "withdrawStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "withdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610182806100206000396000f3fe60806040526004361061004e5760003560e01c80630396cb601461005a578063205c28781461006d578063b760faf91461008c578063bb9fe6bf1461009a578063c23a5cea146100a657600080fd5b3661005557005b600080fd5b61006b6100683660046100c1565b50565b005b34801561007957600080fd5b5061006b610088366004610103565b5050565b61006b61006836600461012f565b34801561006b57600080fd5b3480156100b257600080fd5b5061006b61006836600461012f565b6000602082840312156100d357600080fd5b813563ffffffff811681146100e757600080fd5b9392505050565b6001600160a01b038116811461006857600080fd5b6000806040838503121561011657600080fd5b8235610121816100ee565b946020939093013593505050565b60006020828403121561014157600080fd5b81356100e7816100ee56fea2646970667358221220c2b1306e2a60c32d84ed80e8eb9be2a463aacabc786132e96e508f7b1857d85264736f6c63430008170033";

type MockEntryPointConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockEntryPointConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockEntryPoint__factory extends ContractFactory {
  constructor(...args: MockEntryPointConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockEntryPoint & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockEntryPoint__factory {
    return super.connect(runner) as MockEntryPoint__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockEntryPointInterface {
    return new Interface(_abi) as MockEntryPointInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockEntryPoint {
    return new Contract(address, _abi, runner) as unknown as MockEntryPoint;
  }
}
