/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISessionKeyStore,
  ISessionKeyStoreInterface,
} from "../../../contracts/SmartAccount.sol/ISessionKeyStore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "key",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "durationSeconds",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxTradeSize",
        type: "uint256",
      },
      {
        internalType: "bytes32[]",
        name: "allowedPairs",
        type: "bytes32[]",
      },
    ],
    name: "createSessionKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "key",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "pair",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "isValidSessionKey",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "key",
        type: "address",
      },
    ],
    name: "revokeSessionKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISessionKeyStore__factory {
  static readonly abi = _abi;
  static createInterface(): ISessionKeyStoreInterface {
    return new Interface(_abi) as ISessionKeyStoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISessionKeyStore {
    return new Contract(address, _abi, runner) as unknown as ISessionKeyStore;
  }
}
